import '../css/Home.css'
import React from 'react'

export default class HomeComponent extends React.Component {
    render() {
        return (
            <div className='c12'>
                <h1>This is</h1>
                <h1>Home Component</h1>
                <h2>Home Component</h2>
                <h3>Home Component</h3>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
                <div>Home Component</div>
            </div>
        )
    }
}
